language: python
python:
  - 2.7

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce

install:
  - pip install -r requirements.txt
  - docker build --build-arg QGIS_TEST_VERSION=${QGIS_TEST_VERSION}  .docker

jobs:
  include:
    - stage: test
      env:
        QGIS_TEST_VERSION="latest"
      script: docker-compose -f .docker/docker-compose.travis.yml run qgis .docker/run-docker-tests.sh
#    - stage: test
#      env:
#        QGIS_TEST_VERSION="2.99-alpha"
#      script: docker-compose -f .docker/docker-compose.travis.yml run qgis /usr/src/.docker/run-docker-tests.sh

#    - stage: deploy
#      if: tag IS present
#      install:
#        - pip install -r requirements.txt
#      script: scripts/ci/deploy.sh

#env:
#  global:
#    - OSGEO_USERNAME=mkuhn
#    # Inject OSGEO_PASSWORD matching the OSGEO_USERNAME
#    # Generate with the following command for proper special characters support
#    #     travis encrypt OSGEO_PASSWORD=\''Your super secret password!'\'
#    - secure: "eEt7uqkJBoJWgrDk4rwFHuL0zudEzdj+3kiANRhJXmmmeR46zVkyt3naJGIE2OjAUV3g9s06JciGNzyUxgjhl0UBj2CNqgQd1NTUWdJEiumD00geXyTnLfyz6vl0DG/S1zW9SAtCNkwHGwg6z/MedS1kODj0RApZUmq1MVE+FaremryLp61MCPVuuVslX65Te1XbfKGiQLjSa4TjRzUClL2xSHzFWmAHYIrPoib1UoS5F/BJEXCqR8bTtR9pt72V56PeV5nvReXe5fhukOylxtf3/c+bNpEM2f51tr5f2IrOMHYPD6JfpvBp1SWqdVAmx0P8iLaFa3tXTtC7HFyKhib9k6auE4u4/c4XN46beic6cKNtYkbJ4ttQg8TDA+h4y66VumoRWgJrYxv3OJLTj8SQEQCXEkdYSzpvwdnw/hi3hCkwa2Yyl9VGrcIzx3/xBQwnCZBw1sqNdEHakeKu/XogPt/0VBRzaFvDjhHofyHcOcz3z/IPPtEj9WV7nruWCkeR+kkhPZPrS1+2GnG0BfHhJh8yUSxOfcf6NUR/3BNlO3csVXU594Ct8vQ7VBiEx2Vj4BAhANBLLR1vNXr70c5v+2R5KKY/DeZwtd9cEEbY9koxIpwRwZj8ye5DpZo1+rTxNY17V0WaWIt9ZXheBx2iSlGiMSdBIYQqyyrWXZ0="
#    # OAUTH_TOKEN <- personal access token for github to deploy on "releases"
#    # https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
#    - secure: "51yV6CNJCRpQ0X66fRYT/SSbCq9AM1UFl4BlcNKMkKQ/3llcf6XWM6HVQ5wiAgZSeIut0aGun2VpmRkgSxpoORUCHERth6vDjRyIELYxcq26otfM8okWYh61H2oggiVEFp0ACMl6a3dphzsFMT+7LLDJ1o45cV49VuVbbX4Pa/3eBeSA/TVU03PZE7nSNDGRcHoZM/WTkPDEbfCr8NaF/LD5E5LPLe3XThrZPeBOkQAJP4QIrIvdLPUH7yfbjDU1PQi/ys0FbYbPzC9TiaUA5R+VcAh4J6q2Dhjtl0Q9g/GzzJUj2zF2RoGGk0AsLdRP0dxoNM4FD9pAvpEfTZZFU1xOj8PKnniM6ry5oeaNJwevIXNB6qsHVWbOHIPGzsYG7acRukZxhzOB2x8QyqmdJoVPhUvcKQ1Mypn9b0qE8f0QwtTNPJAvCIGm+iK+hnj0wuQ9+pK/YofDMBVCPdITkZ3F1OzIdg3kvvoa7lmv/HHTuKy0eqqw03+j3wMDoy0TmlfV6iHzAeYYm/mbQzUt64XfFVUJKcvv6Y2zCbfgodEEu/QZmnJJb8/qw/tTxJHp7tcVUVSxBFFYdMIFfKKqwwnh3vJgnw73YoSrtfezLTNkb4q3NqZcJ5nBkhPjZziBFUQcIuL5XSNqSfXo3WjSvSN0rgVvjBbgTccISqhOprI="